App\Entity\Tag:
    exclusion_policy: All
    custom_accessor_order: [id, name, color]
    properties:
        id:
            include: true
        name:
            include: true
        color:
            include: true
        timesheets:
            exclude: true
